---
parameters:
  - { name: publisherId, type: string, default: "" }
  - { name: extensionId, type: string, default: "" }
  - { name: extensionName, type: string, default: "" }
  - { name: extensionPricing, type: string, default: "free" }
  - { name: extensionTag, type: string, default: "" }
  - { name: extensionVisibility, type: string, default: "private" }

jobs:
  - job: publish
    displayName: "Publish ${{ parameters.extensionVisibility }}"
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: spec
          versionSpec: 20.x

      - task: Npm@1
        displayName: Install dependencies
        inputs:
          command: custom
          customCommand: run ci
          verbose: false
        env:
          NODE_ENV: production

      - task: Npm@1
        displayName: Run build
        inputs:
          command: custom
          customCommand: run build
          verbose: false

      - task: TfxInstaller@5
        inputs:
          version: "v0.x"

      - task: QueryAzureDevOpsExtensionVersion@5
        name: QueryVersion
        inputs:
          connectTo: "VsTeam"
          connectedServiceName: "https://marketplace.visualstudio.com"
          publisherId: ${{ parameters.publisherId }}
          extensionId: argocd-installer
          extensionTag: ${{ parameters.extensionTag }}
          versionAction: "Patch"

      - ${{ if ne(parameters.extensionTag, '') }}:
          - bash: |
              echo "Find all task.json files and update the "name" property in place using yq"
              find . -type f -name "task.json" | while read -r file; do
                echo "Updating $file"
                yq eval '.name = (.name + "${{ upper(parameters.extensionTag) }}")' -i "$file"
              done
            displayName: "Update task's names with tag"

      - task: PackageAzureDevOpsExtension@5
        inputs:
          publisherId: "${{ parameters.publisherId }}"
          extensionId: "${{ parameters.extensionId }}"
          extensionTag: "${{ parameters.extensionTag }}"
          extensionName: "${{ parameters.extensionName }}"
          extensionVisibility: "${{ parameters.extensionVisibility }}"
          extensionPricing: "${{ parameters.extensionPricing }}"
          extensionVersion: "$(Extension.Version)"
          updateTasksVersion: true
          updateTasksVersionType: "patch"

      - ${{ if eq(parameters.extensionVisibility, 'private') }}:
          - task: PublishAzureDevOpsExtension@5
            inputs:
              connectTo: "VsTeam"
              connectedServiceName: "https://marketplace.visualstudio.com"
              fileType: "manifest"
              publisherId: ${{ parameters.publisherId }}
              extensionId: ${{ parameters.extensionId }}
              extensionTag: ${{ parameters.extensionTag }}
              extensionName: ${{ parameters.extensionName }}
              extensionPricing: ${{ parameters.extensionPricing }}
              extensionVisibility: ${{ parameters.extensionVisibility }}
              extensionVersion: "$(Extension.Version)"
              updateTasksId: false
              updateTasksVersion: true
              updateTasksVersionType: "patch"
              ${{ if eq(parameters.extensionVisibility, 'private') }}:
                shareWith: ${{ split(variables['System.CollectionUri'], '/')[3] }}
