---
parameters:
  # Azure DevOps organization generic service connection. URL should be in the format https://dev.azure.com/organization
  - { name: organizationConnection, type: string, default: "" }
  # Task name to lookup for the updated version. One of taskName or taskId should be provided
  - { name: taskName, type: string, default: "" }
  # Task ID to lookup for the updated version. One of taskName or taskId should be provided
  - { name: taskId, type: string, default: "" }
  # Number of retries to perform the lookup
  - { name: retryCount, type: number, default: 10 }
  - { name: delayForMinutes, type: number, default: 2 }

jobs:
  - job: wait
    displayName: Wait
    dependsOn: publish
    timeoutInMinutes: 60
    pool: server
    variables:
      System.Debug: true
      version: $[ dependencies.publish.outputs['QueryVersion.Extension.Version'] ]
    steps:
      - task: Delay@1
        inputs:
          delayForMinutes: ${{ parameters.delayForMinutes }}

      - task: InvokeRESTAPI@1
        displayName: "Wait for the updated task to be available"
        retryCountOnTaskFailure: ${{ parameters.retryCount }}
        inputs:
          connectionType: "connectedServiceName"
          serviceConnection: "${{ parameters.organizationConnection }}"
          method: "GET"
          urlSuffix: "/_apis/distributedtask/tasks/${{ parameters.taskId }}"
          waitForCompletion: "false"
          headers: '{ "Authorization": "Bearer $(System.AccessToken)" }'
          ${{ if ne(parameters.taskId, '') }}:
            successCriteria: eq(jsonpath('.value[0].contributionVersion')[0], variables['version'])
          ${{ elseif ne(parameters.taskName, '') }}:
            successCriteria: eq(jsonpath('.value[?(@.name==''${{ parameters.taskName }}'')].contributionVersion')[0], variables['version'])
          ${{ else }}:
            # Fail the task if either taskName or taskId is not provided
            successCriteria: eq(false, true)
