---
resources:
  pipelines:
    - pipeline: e2e
      source: bonddim.argocd-azure-devops-task-e2e
      trigger:
        branches:
          include:
            - main

trigger: none
pr: none

stages:
  - stage: Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: templates/publish.yaml
        parameters:
          marketplaceConnection: e5af4fa9-9ce8-48be-88bf-ad06b71c2017
          publisherId: bonddim
          extensionId: argocd-installer
          extensionName: Argo CD CLI Installer
          extensionVisibility: public

      - template: templates/wait.yaml
        parameters:
          organizationConnection: 2f23d378-bcdb-4206-b7aa-e062138a0e4a
          taskId: bf9f5d10-e985-11ef-80f2-00155de5031d

      - job: Release
        dependsOn: publish
        variables:
          version: $[ dependencies.publish.outputs['QueryVersion.Extension.Version'] ]
        steps:
          - checkout: none
          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 6de9605e-eb3c-4e78-8ef0-41ea94aa7918
              repositoryName: $(Build.Repository.Name)
              action: create
              changeLogCompareToRelease: lastFullRelease
              changeLogType: commitBased
              target: $(Build.SourceVersion)
              tagSource: userSpecifiedTag
              tag: $(version)
